project:
  type: website
  output-dir: docs

# Meta
description-meta: "Personal Website of Shubha Sankar Banerjee"
author-meta: "Shubha Sankar Banerjee"

website:
  title: "S S Banerjee"
  image: "files/profiles/profile1.JPG"  # Replace with your actual image path
  description: "PhD Student, Department of Statistics, University of Pittsburgh"

  navbar:
    background: light

    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd

    right:
      - text: CV
        href: files/pdf/cv-shubha-june25.pdf
      - icon: github
        href: https://github.com/shubha3
        target: _blank
      - icon: twitter
        href: https://x.com/ssbanerjee461
        target: _blank

  page-navigation: true

  page-footer:
    left: "[Shubha Sankar Banerjee](https://shubha3.github.io) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: "Built using [Quarto Academic Template](https://github.com/drganghe/quarto-academic-website-template)"
    right:
      - icon: github
        href: https://github.com/shubha3
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true
  draft-mode: unlinked
  open-graph: true
  twitter-card: true

  site-url: "https://shubha3.github.io"

  repo-url: https://github.com/shubha3/shubha3.github.io

  google-analytics:
    tracking-id: ""  # Add tracking ID if needed
    anonymize-ip: true

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toggle-theme: true
    default-mode: light
    css: custom-styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    include-in-header: "files/includes/_academic.qmd"
